//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.03 at 12:19:05 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://integracja.pl/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.integracja.soap;
