//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.29 at 11:42:55 AM CEST 
//


package com.example.projekt.soap.cpu.pl.integracja.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cores" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="threads" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="launch_date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="lithography" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="base_frequency" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="turbo_frequency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tdp" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="socket" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="manufacturer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cores",
    "threads",
    "name",
    "launchDate",
    "lithography",
    "baseFrequency",
    "turboFrequency",
    "tdp",
    "socket",
    "manufacturer"
})
@XmlRootElement(name = "addCpuRequest")
public class AddCpuRequest {

    protected int cores;
    protected int threads;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "launch_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar launchDate;
    protected int lithography;
    @XmlElement(name = "base_frequency")
    protected int baseFrequency;
    @XmlElement(name = "turbo_frequency", required = true)
    protected String turboFrequency;
    protected int tdp;
    @XmlElement(required = true)
    protected String socket;
    @XmlElement(required = true)
    protected String manufacturer;

    /**
     * Gets the value of the cores property.
     * 
     */
    public int getCores() {
        return cores;
    }

    /**
     * Sets the value of the cores property.
     * 
     */
    public void setCores(int value) {
        this.cores = value;
    }

    /**
     * Gets the value of the threads property.
     * 
     */
    public int getThreads() {
        return threads;
    }

    /**
     * Sets the value of the threads property.
     * 
     */
    public void setThreads(int value) {
        this.threads = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the launchDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLaunchDate() {
        return launchDate;
    }

    /**
     * Sets the value of the launchDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLaunchDate(XMLGregorianCalendar value) {
        this.launchDate = value;
    }

    /**
     * Gets the value of the lithography property.
     * 
     */
    public int getLithography() {
        return lithography;
    }

    /**
     * Sets the value of the lithography property.
     * 
     */
    public void setLithography(int value) {
        this.lithography = value;
    }

    /**
     * Gets the value of the baseFrequency property.
     * 
     */
    public int getBaseFrequency() {
        return baseFrequency;
    }

    /**
     * Sets the value of the baseFrequency property.
     * 
     */
    public void setBaseFrequency(int value) {
        this.baseFrequency = value;
    }

    /**
     * Gets the value of the turboFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTurboFrequency() {
        return turboFrequency;
    }

    /**
     * Sets the value of the turboFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTurboFrequency(String value) {
        this.turboFrequency = value;
    }

    /**
     * Gets the value of the tdp property.
     * 
     */
    public int getTdp() {
        return tdp;
    }

    /**
     * Sets the value of the tdp property.
     * 
     */
    public void setTdp(int value) {
        this.tdp = value;
    }

    /**
     * Gets the value of the socket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocket() {
        return socket;
    }

    /**
     * Sets the value of the socket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocket(String value) {
        this.socket = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }

}
