//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.29 at 11:42:55 AM CEST 
//


package com.example.projekt.soap.cpu.pl.integracja.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.integracja.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.integracja.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCpuByIdRequest }
     * 
     */
    public GetCpuByIdRequest createGetCpuByIdRequest() {
        return new GetCpuByIdRequest();
    }

    /**
     * Create an instance of {@link GetCpuByIdResponse }
     * 
     */
    public GetCpuByIdResponse createGetCpuByIdResponse() {
        return new GetCpuByIdResponse();
    }

    /**
     * Create an instance of {@link Cpu }
     * 
     */
    public Cpu createCpu() {
        return new Cpu();
    }

    /**
     * Create an instance of {@link GetAllCpusRequest }
     * 
     */
    public GetAllCpusRequest createGetAllCpusRequest() {
        return new GetAllCpusRequest();
    }

    /**
     * Create an instance of {@link GetAllCpusResponse }
     * 
     */
    public GetAllCpusResponse createGetAllCpusResponse() {
        return new GetAllCpusResponse();
    }

    /**
     * Create an instance of {@link AddCpuRequest }
     * 
     */
    public AddCpuRequest createAddCpuRequest() {
        return new AddCpuRequest();
    }

    /**
     * Create an instance of {@link AddCpuResponse }
     * 
     */
    public AddCpuResponse createAddCpuResponse() {
        return new AddCpuResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link UpdateCpuRequest }
     * 
     */
    public UpdateCpuRequest createUpdateCpuRequest() {
        return new UpdateCpuRequest();
    }

    /**
     * Create an instance of {@link UpdateCpuResponse }
     * 
     */
    public UpdateCpuResponse createUpdateCpuResponse() {
        return new UpdateCpuResponse();
    }

    /**
     * Create an instance of {@link DeleteCpuRequest }
     * 
     */
    public DeleteCpuRequest createDeleteCpuRequest() {
        return new DeleteCpuRequest();
    }

    /**
     * Create an instance of {@link DeleteCpuResponse }
     * 
     */
    public DeleteCpuResponse createDeleteCpuResponse() {
        return new DeleteCpuResponse();
    }

}
